### PR TITLE
Enable workflow schema update.

### PR DESCRIPTION
**Pull request by jangsutsr**
Connect #284.

See updates in `WORKFLOWS.md` for behavior changes.

### CODE REVIEW

**Comment by AlanCoding** [comment]
It looks like the node ids are returned with a simple schema GET,

```
$ tower-cli workflow schema asdf
- id: 1
  job_template: 18
```

I see why that might be desired to add, but I'm wondering if it was intended.

**Comment by jangsutsr** [comment]
@AlanCoding No it's not. I just don't want to explicitly add that handling and increase code confuse.

**Comment by AlanCoding** [comment]
Oh yeah, that's totally fine. I will just want to check that creation of a new WFJT will work the same given the schema output.

**Comment by AlanCoding** [comment]
This looks excellent with my testing so far. Here are some materials that I'm gathering for this, along with the other feature about looking up inventory sources by a partial name:

https://github.com/AlanCoding/tower-cli/commit/4096c6db4e0dd304228365db7e12d31d0292aa40

I've been testing switching between two different schemas, and it's going very well. When telling it to apply the schema example after it already exists, I see 8 GET requests and no changes made. That is _nice_ idempotency.

I still might want to cycle through one more example early tomorrow with a more complex branching structure. So far this is incredible.

**Comment by AlanCoding** [comment]
The culmination of my testing:

Schema A

```yaml
# Branch that has deeply nested content removed  going to schema B
- job_template: workflow JT
  failure_nodes:
    - inventory_source: tower script1 (workflow demo
  success_nodes:
  - project: Ansible Examples
    always_nodes:
    - job_template: workflow JT
      success_nodes:
      - job_template: workflow JT

# Branch that is modified going to schema B
- job_template: workflow JT2
  failure_nodes:
  - job_template: workflow JT2
  - job_template: workflow JT
  success_nodes:
  - job_template: workflow JT2
  - job_template: workflow JT

# Branch that is deleted going to schema B
- project: Ansible Examples
  always_nodes:
  - inventory_source: tower script1 (workflow demo
  - inventory_source: tower script2 (workflow demo
```

Schema B

```yaml
# Branch that has deeply nested content removed  going to schema B
- job_template: workflow JT
  failure_nodes:
    - inventory_source: tower script1 (workflow demo
  success_nodes:
  - project: Ansible Examples
    always_nodes:
    - job_template: workflow JT

# Branch that is modified going to schema B
- job_template: workflow JT2
  failure_nodes:
  - inventory_source: tower script1 (workflow demo
  - inventory_source: tower script2 (workflow demo
  success_nodes:
  - project: Ansible Examples
  - job_template: workflow JT
```

This feature seems to be able to swap back and fourth between A and B. I see DELETEs and POSTs right where I expect them. Reapply either A or B after that state has already been reached, and it makes only GET requests, no changes are done.

I have actually avoided the indeterminate cases where 2 of the same JTs are on the same level next to each other. I presume that you have tested this, but I don't think it's high enough customer value to bother with right now. I would recommend that schema authors just avoid that, and my example schemas will, thus, follow the rule as well.

Also, we can't really have any PATCH actions with the approach to schema authoring I'm testing. I presume we would if the ids were used, but I would also hesitate to directly suggest that method as a reusable and sharable format.

This is tremendously complex, and executed perfectly.

**Pull request merged**
