### PR TITLE
remove the unnecessary `lib` path and `package_dir` specification

### PR DESCRIPTION
**Pull request by ryanpetrello**
this also fixes breakage of `pip install -e .`

### CODE REVIEW

**Comment by AlanCoding** [comment]
Travis says that it passed, but if you click into it, it looks like other python versions are failing. Those look slightly familiar, but I don't see them on other recent pull requests. I might re-run the tests in a second to be sure.

**Comment by AlanCoding** [comment]
maybe it had a stale link. I had seen https://travis-ci.org/ansible/tower-cli/builds/206680594, but maybe this isn't the most recent.

**Comment by ryanpetrello** [comment]
The most recent build I see seems to be passing: https://travis-ci.org/ansible/tower-cli/builds/206686598

**Comment by jangsutsr** [comment]
@ryanpetrello My salute to you! A `lib` directory is so confusing (a dynamic runtime library in a Python repo?) and I've always wanted it removed 👍

**Pull request merged**
