### PR TITLE
Allow for adding/removing org admins.

### PR DESCRIPTION
**Pull request by wenottingham**
There might be a more clean way to do this, but this is the simple way.

### CODE REVIEW

**Comment by AlanCoding** [comment]
Haven't tested yet, but looks good by the code. The test failure was because of a pedantic flake8 thing, and then because tests aren't written yet.

Sometime, I would also like to get around to renaming `associate` to `associate_user`.

Another question - does the user have to be in the organization before you can appoint them admin?

**Comment by AlanCoding** [comment]
I tested this branch, and I'm happy with how it works. It appears that you do not need to be in an organization in order to be appointed its admin. If that behavior is okay, then I give the :+1: to this feature. Here are commands I used to test:

```bash
tower-cli user delete --username=bio_citizen
tower-cli user delete --username=hyrule_citizen
tower-cli user delete --username=ronin

tower-cli user create --username=bio_citizen --password="password" --email=asdf@bio.com --first-name=Jon --last-name=Smith
tower-cli user create --username=hyrule_citizen --password="password" --email=asdf@hyrule.gov --first-name=Jon --last-name=Smith
tower-cli user create --username=ronin --password="password" --email=asdf@gmail.com --first-name=Jon --last-name=Smith

tower-cli organization associate --organization="Bio Inc" --user=bio_citizen
tower-cli organization associate --organization="Hyrule Ventures" --user=hyrule_citizen

tower-cli organization associate_admin --organization="Bio Inc" --user=bio_citizen
tower-cli organization associate_admin --organization="Hyrule Ventures" --user=hyrule_citizen
tower-cli organization associate_admin --organization="Hyrule Ventures" --user=ronin

tower-cli organization disassociate_admin --organization="Bio Inc" --user=bio_citizen
tower-cli organization disassociate_admin --organization="Hyrule Ventures" --user=hyrule_citizen
tower-cli organization disassociate_admin --organization="Hyrule Ventures" --user=ronin
```

**Comment by wenottingham** [comment]
OK. Should I fix the flake8 and repush, or merge and then fix?

**Comment by wenottingham** [comment]
Merged your fix into this branch. OK to merge, or does it need to go to a particular branch?

**Comment by AlanCoding** [comment]
Good to merge now. However, I noticed that it isn't getting fully linked to its corresponding issue. You referenced the PR in the issue, but it is picky. This should do it:

Fixes #100

**Pull request merged**
