### PR TITLE
Fix the res_name for workflow labels

### LINKED ISSUE #663: "tower-cli send" failed when label already existed
- Tower CLI 3.3.2
- AWX 3.0.0.0
- Ansible 2.7.6

```
tower-cli receive --all --format json | jq ' .[] | select(.asset_type == "workflow") ' | jq -s '.' > workflow.json
tower-cli send workflow.json
```

If there is a label listed in workflow.json, but this same label (ie. with the same name) has already previously been created inside AWX prior to the execution of the "tower-cli send" command, the following error would occur and the "send" command would stop.

```

*** DETAILS: Checking for an existing record. *********************************
GET http://<awx_url>/api/v2/labels/
Params: [('name', 'A LABEL')]

*** DECISION: Record already exists, and --force-on-exists is off; do nothing. 

Added label A LABEL
Traceback (most recent call last):
  File "/bin/tower-cli", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 370, in send
    sender.send(source, prevent, exclude, secret_management)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 294, in send
    self.import_labels(existing_object, relations[a_relation], asset_type)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 1014, in import_labels
    'label': created_label['id'],
  File "/usr/lib/python2.7/site-packages/tower_cli/models/fields.py", line 198, in method
    return internal_method(method._relationship, obj_pk, other_obj_pk)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 576, in _assoc
    url = self.endpoint + '%d/%s/' % (me, url_fragment)
TypeError: %d format: a number is required, not NoneType
```

There is currently no "--force-on-exists" option available for "tower-cli send" command, so I am not sure how to overcome this.

Thanks

### PR DESCRIPTION
**Pull request by jainnikhil30**
Fixes #663

### CODE REVIEW

**Comment by AlanCoding** [comment]
trying to test that this doesn't break CLI use...

```
$ tower-cli workflow associate_label --workflow="massively empty" --label=foo
Error: no such option: --workflow  Did you mean --workflow-job-template?
$ tower-cli workflow associate_label --workflow-job-template="massively empty" --label=foo
Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/cli/bin/tower-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.3', 'console_scripts', 'tower-cli')()
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/ansible_tower_cli-3.3.3-py2.7.egg/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/ansible_tower_cli-3.3.3-py2.7.egg/tower_cli/cli/action.py", line 46, in parse_args
    return super(ActionSubcommand, self).parse_args(ctx, args)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1396, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1681, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1365, in full_process_value
    value = self.process_value(ctx, value)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1355, in process_value
    return self.type_cast_value(ctx, value)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1344, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/core.py", line 1342, in _convert
    return self.type(value, self, ctx)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/ansible_tower_cli-3.3.3-py2.7.egg/tower_cli/cli/types.py", line 128, in convert
    resource = tower_cli.get_resource(self.resource_name)
  File "/Users/alancoding/.virtualenvs/cli/lib/python2.7/site-packages/ansible_tower_cli-3.3.3-py2.7.egg/tower_cli/__init__.py", line 32, in get_resource
    module = importlib.import_module('tower_cli.resources.%s' % name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named workflow_job_template
```

I get that the send command is a different use case, and it might be difficult to satisfy both.

**Comment by jainnikhil30** [comment]
@AlanCoding 

My bad. Thanks for testing the cli use, which this PR is breaking. I think I can try to make change in send to accomplish this. I will update the PR.

**Comment by jainnikhil30** [comment]
@AlanCoding 

I have made the change in send now. Instead of it using "workflow_job_template" it should use "workflow" when its associating and dissociating labels.

**Comment by jainnikhil30** [comment]
@john-westcott-iv 

Could you please take a look at this ?

**Comment by AlanCoding** [comment]
I wonder if we can get rid of this `keyword_arg_template_id` variable and use `asset_type` instead.

**Comment by jainnikhil30** [comment]
@AlanCoding 

Yeah makes sense. I have removed `keyword_arg_template_id` and now it uses asset_type directly.

**Pull request merged**
