### PR TITLE
Added 'verify_ssl' configuration flag.

### PR DESCRIPTION
**Pull request by wybczu**
Also suppress InsecureRequestWarning urllib3 warnings when verify_ssl == False. This PR solves  #26.

### CODE REVIEW

**Comment by wybczu** [comment]
Hi @lukesneeringer,

This PR is related to cf37c28, but it suppress only `InsecureRequestWarning`. Can you take a look at this PR?

**Comment by amokan** [comment]
this config feature would be helpful for me as well (cc @lukesneeringer @wybczu )

**Comment by tristanbes** [comment]
Can you rebase it so an admin can merge this please ? it'd be great :-)

**Comment by robbiet480** [comment]
:+1:. Annoying/scary to others that our SSL isn't passing, because we have an internal CA which our CI/CD doesn't recognize.

**Comment by wybczu** [comment]
Also it is possible to specify custom [CA bundle](http://docs.python-requests.org/en/latest/api/#requests.request) via `verify_ssl` to verify SSL certificate.

**Comment by wybczu** [comment]
On second thought this warning **should** be displayed. Not verifying ssl certificate is a big security issue, it makes MITM attacks easy :) I'm closing this pull request and I will create another one.

**Comment by ccollicutt** [comment]
@wybczu What made you change your mind? What's wrong with turning off ssl warnings? If it's not default, then I'd like to be able to turn if off. What if the particular tower instance is just a test instance and we don't want to take the time to deploy proper certificates? Or what if it was a situation where I don't manage the service?

**Comment by wybczu** [comment]
@ccollicutt as a user I would like to know when SSL verification is disabled (warnings should be displayed).

If you don't want to deploy proper cert you can always download tower's certificate (bash oneliner) and pass path to it e.g. via `ca_path` option. What do you think about such solution?

**Comment by flmmartins** [comment]
Hi, was this merged?

I am trying to disable the verification it but no success.

**Pull request closed without merging**
