### PR TITLE
Now storing password in config files as base64 encoded

### PR DESCRIPTION
**Pull request by john-westcott-iv**
This will base64 encode the password fields in the various config files. It will not auto-re-encode existing files but the next time config writes the password to the file it will become encoded.

### CODE REVIEW

**Comment by AlanCoding** [comment]
resolves https://github.com/ansible/tower-cli/issues/134

**Comment by AlanCoding** [comment]
Seems the same arguments could apply to tokens @ryanpetrello what are your thoughts?

**Comment by AlanCoding** [comment]
Thinking more on this... another argument might be that this would actually be really non-standard from an Ansible perspective. Look at how we write credential files for other cloud sources in AWX:

https://github.com/ansible/awx/blob/devel/awx/plugins/inventory/cloudforms.ini.example

One of tower-cli's primary purposes is to be the upstream library for the tower_* modules, and soon we'll be adding the inventory plugin. Correspondingly, the config file that we're using now as `.tower_cli.cfg` would then likely be ported into the AWX credential creation, and no other similar examples use encryption or obfuscation. This might still work, but I would conservatively prefer to hold off until those changes have been implemented.

**Comment by john-westcott-iv** [comment]
@ryanpetrello 
I don't think the intent is "Secure" I think its obfuscation and as long as we don't tout it as being secure hopefully no one is under a false sense of security. 

Many companies I know just don't want "plain text passwords" in files but they don't say they require security. At a past company someone was telling me that something to the affect of: if someone has to do something to get a password (decrypt it, unencoded it, etc) it proves intent whereas "just seeing it" and using it could be interpreted as an accident (disclaimer: I'm not a lawyer).

Also, tokens will be cool as long as people have the automation to refresh the token. i.e. if someone was using Jenkins with TowerCLI (which hopefully they are using my plugin) they would need something to rotate Jenkins token (if they set it to expiring). Also, until people have migrated to a version of Tower which supports Tokens us telling them to use a token is kind of pointless. 

@AlanCoding 
When using TowerCLI via Ansible/Tower it makes sense to use a vaulted password/Tower credential and you don't need a config file so this change would be mute. When coding it, I actually thought about using a vaulted password in the config file but then we would need to require ansible libraries on the box. I also thought about actually encrypting the password as well but didn't want to require libcrypt or another library (plus were open source so we couldn't 'hide' the decryption key). As for other files within Ansible I would say "see above". At my client they don't even keep the Tower inventory file around after building a Tower cluster because it has unencrypted passwords in the file, it is only tolerated on the filesystem for the duration of the buildout.

**Pull request closed without merging**
