### PR TITLE
Custom certificate support

### PR DESCRIPTION
**Pull request by jangsutsr**
Connect #200 and #194.

*PLEASE DO NOT MERGE THIS PR BEFORE IT IS FULLY TESTED!*

### CODE REVIEW

**Comment by jangsutsr** [comment]
Test by purposely generating an inaccurate certificate:
```
(tower_cli_devel) dyn-160-39-224-155:~ sitan$ tower-cli version -v --certificate test.crt
Tower CLI 3.0.0
GET https://ec2-23-20-65-169.compute-1.amazonaws.com/api/v1/config/
Params: {}

/Users/sitan/tower_cli_devel/lib/python2.7/site-packages/requests-2.11.1-py2.7.egg/requests/packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for ec2-23-20-65-169.compute-1.amazonaws.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
SSL connection failed:
hostname 'ec2-23-20-65-169.compute-1.amazonaws.com' doesn't match u'www.ansible.com'

Suggestion: add the correct http:// or https:// prefix to the host configuration.
Error: Could not establish a secure connection. Please add the server to your certificate authority.
You can run this command without verifying SSL with the --insecure flag, or permanently disable verification by the config setting:

 tower-cli config verify_ssl false
```
```
(tower_cli_devel) dyn-160-39-224-155:~ sitan$ tower-cli version -v --certificate test.crt --insecure
Tower CLI 3.0.0
GET https://ec2-23-20-65-169.compute-1.amazonaws.com/api/v1/config/
Params: {}

Ansible Tower 3.0.0
```
and
```
(tower_cli_devel) dyn-160-39-224-155:~ sitan$ cat .tower_cli.cfg
[general]
host = ec2-23-20-65-169.compute-1.amazonaws.com
username = admin
password = password
verify_ssl = false

(tower_cli_devel) dyn-160-39-224-155:~ sitan$ tower-cli version -v --certificate test.crt
Tower CLI 3.0.0
GET https://ec2-23-20-65-169.compute-1.amazonaws.com/api/v1/config/
Params: {}

Ansible Tower 3.0.0
```

**Comment by AlanCoding** [comment]
Let's see if we can get someone to help us by testing this branch with a valid certificate.

**Comment by jangsutsr** [comment]
Test using accurate certificate:
```
(tower_cli_devel) dyn-160-39-224-155:~ sitan$ cat .tower_cli.cfg
[general]
host = https://ec2-54-227-95-173.compute-1.amazonaws.com
username = admin
password = password
verify_ssl = true

(tower_cli_devel) dyn-160-39-224-155:~ sitan$ tower-cli host list --certificate www.ansible.com -v
*** DETAILS: Getting records. *************************************************
GET https://ec2-54-227-95-173.compute-1.amazonaws.com/api/v1/hosts/
Params: {u'page': 1}

/Users/sitan/tower_cli_devel/lib/python2.7/site-packages/requests-2.11.1-py2.7.egg/requests/packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for ec2-54-227-95-173.compute-1.amazonaws.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
== ========= ========= =======
id   name    inventory enabled
== ========= ========= =======
 1 localhost         1    true
== ========= ========= =======
```

**Comment by AlanCoding** [comment]
Interesting, I wonder if it still produces that message with different versions of requests. But even with that, it looks like the requested issue has been solved.

**Comment by jangsutsr** [comment]
@AlanCoding We are using the latest stable version of requests, and [the corresponding issue is still open](https://github.com/shazow/urllib3/issues/497). Let's use help docs for now.

**Pull request merged**
