### PR TITLE
Tentative new styled debug log message.

### PR DESCRIPTION
**Pull request by jangsutsr**
Connect to issue #178 .

### CODE REVIEW

**Comment by AlanCoding** [comment]
I'm not liking this much in its current form because of the impact that it is having on blank lines.

```
tower-cli credential create --name blank_credential2 --kind ssh --organization Default -v
*** DETAILS: Checking Project API Details. ************************************
*** OPTIONS http://192.168.100.128:8013/api/v1/credentials/ *******************
***  **************************************************************************
*** DETAILS: Checking for an existing record. *********************************
*** GET http://192.168.100.128:8013/api/v1/credentials/ ***********************
*** Params: {'organization': 1, 'kind': 'ssh', 'name': u'blank_credential2'} **
***  **************************************************************************
*** DETAILS: Writing the record. **********************************************
*** POST http://192.168.100.128:8013/api/v1/credentials/ **********************
*** Data: {'kind': 'ssh', 'name': u'blank_credential2', 'organization': 1} ****
***  **************************************************************************
Resource changed.
== ================= ==== ======== 
id       name        kind username 
== ================= ==== ======== 
16 blank_credential2 ssh
== ================= ==== ======== 
```

I think it's a good concept, but it needs to be narrowed to address only the very specific case of an oversized "details" message. Even the "Data:" and "Params:" would probably do best to avoid the asterisks.

**Comment by jangsutsr** [comment]
@AlanCoding Thx for pointing out. Double checked to find I made a mistake: padding with asterisks *only* applies to messages with headers. Will correct it and add test cases.

**Comment by jangsutsr** [comment]
@AlanCoding It should be working now: only messages with header will be padded.

**Comment by AlanCoding** [comment]
:+1: works fine as far as I've tested it now

**Pull request merged**
